### ISSUE TITLE
OptimisticQLearner

### ISSUE THREAD

**Issue by sudeepraja** [iosband/TabulaRL#1]
In the optimistic Q Learning agent, I am not sure why you would index qVals with state and timestep instead of just state. I implemented a version which indexes qVals using just the state, it seems to get better rewards:

class QLearner(FiniteHorizonTabularAgent):

```
def __init__(self, nState, nAction, epLen,
             learnRate=0.01, epsilon=0.05, qInit=False,**kwargs):
    # Fill in the variables
    self.nState = nState
    self.nAction = nAction
    self.epLen = epLen
    self.learnRate = learnRate
    self.epsilon = epsilon


    qVals = {}
    for state in xrange(self.nState):
        qVals[state] = np.zeros(nAction, dtype=np.float32)
    self.qVals = qVals

def update_obs(self, oldState, action, reward, newState, pContinue, timestep):
    oldQ = self.qVals[oldState][action]
    newQ = reward + pContinue * self.qVals[newState].max()
    self.qVals[oldState][action] = oldQ + self.learnRate * (newQ - oldQ)

def pick_action(self, state, timestep):

    Q = self.qVals[state]
    nAction = Q.size
    noise = np.random.rand()

    if noise < self.epsilon:
        action = np.random.choice(nAction)
    else:
        action = np.random.choice(np.where(Q == Q.max())[0])

    return action
```

I added the QLearner and OptimisticQLearner to chain_experiment.py and tested it on a chain of length 10 for 10000 episodes. 

At the end of 10000 peisodes, the OptimisticQLearner's cumulative reward is -26.1 and and QLearner's is 2794.86.

**Comment by iosband** [comment]
Hi Sudeep,

Thanks for the question. I should probably remove the OptimisticQlearner since I never actually ended up using it in any experiments in [the paper](https://arxiv.org/abs/1607.00215) and, as such it never got any attention/testing.

The reason that the Q-value depends upon state and timestep is because the environment is a finite-horizon MDP. In general, the optimal policy in a finite horizon MDP may not be stationary... although it happens to be in the case of this simple chain environment.

Where the optimal policy is stationary, you probably would expect the stationary agent to learn faster (since it has H-fewer things to learn) although this will not always be the case.

Make sense?

Cheers,
Ian
